# This file is autogenerated from update.sh in the same directory.
{
  gwenhywfar.version = "4.99.20rc4";
  gwenhywfar.sha256 = "1a74gsnn16vwzqvl5pxxwyll8mac4ifql8cpml0d0ckyxcrjzlg9";
  # gwenhywfar.releaseId = "208";
  libchipcard.version = "5.1.3beta";
  libchipcard.sha256 = "149dx68nwmdagq6bvkxq3gvz22wj6d2i63wphrpj0778la55jx46";
  # libchipcard.releaseId = "200";
  aqbanking.version = "5.99.37beta";
  aqbanking.sha256 = "1i3by6mpplzjcmiqd35jcfmcvpswnrpp3p7f4cli0jh1p6js24wk";
  # aqbanking.releaseId = "107";
}
