# This file is autogenerated from update.sh in the same directory.
{
  gwenhywfar.version = "4.99.16beta";
  gwenhywfar.sha256 = "1yr1jqbhg5na6apwssxrp9k88abrycyj20damrj7wap90p68ivwq";
  # gwenhywfar.releaseId = "208";
  libchipcard.version = "5.1.3beta";
  libchipcard.sha256 = "149dx68nwmdagq6bvkxq3gvz22wj6d2i63wphrpj0778la55jx46";
  # libchipcard.releaseId = "200";
  aqbanking.version = "5.99.33beta";
  aqbanking.sha256 = "113wlnnav3k76jlfx17g3sz7fd16q3nm98ca213xgs3vwnq4kbjv";
  # aqbanking.releaseId = "107";
}
