# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1bahnvn6i08gg10r9p012n7xjwhnjk1xq4c70kw6sqr4p53423mn";
    sha256bin64 = "066lvnh18k5982dv9481g9i31g9pq6a8q92g93xkqgj2bipbv6si";
    version = "81.0.4044.26";
  };
  dev = {
    sha256 = "0pxvwjvkajlidk5m7jiqk69mxnxg3h56dr7vpi916r51w17pds0l";
    sha256bin64 = "1jdyp0f2ig4251155db3m7lzd4jlmczcjqqnvdj5nwl2bn3ykc3s";
    version = "82.0.4068.4";
  };
  stable = {
    sha256 = "0wr487drgd030d7p84rdz1cys0c87wbgh2qg3d7qd98gqbfcpss8";
    sha256bin64 = "0kipzd0q3p3wwklcl1fb937xhklc0s76apsfrjwy0jcmcy47blzf";
    version = "80.0.3987.122";
  };
}
