# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "09rdxpq4gprv16xg2llrbbmk19fp5sgl3n9qlhpzzr7a0107nm6f";
    sha256bin64 = "0hvcsbpqvrc7km57myh4xjy6mn32g6w38kziqdrq16f2ychkflv8";
    version = "77.0.3865.35";
  };
  dev = {
    sha256 = "0iywf5r0z10m4c5rd81nkkqpiii0431j6mkxs25gkgfp9jsg1713";
    sha256bin64 = "1v8d99x9k7z9ll75k0ddmfh08rlv2xgv1vvy5czk2x4pv1sh1pki";
    version = "78.0.3880.4";
  };
  stable = {
    sha256 = "0vfjfxsqf8jrmd7y08ln1lpbilwi150875zn2bawwdq87vd3mncc";
    sha256bin64 = "1c5rlqgshv5295wg5cji12z2b38l6a81l94spmzr46h5z9nn1gqx";
    version = "76.0.3809.100";
  };
}
