# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "07gdxk3g5l16z83k9wl3yxakrx5flb2cqvpda3gnc5sjvb66wa64";
    sha256bin64 = "1wpdasd7qb40wcm7vjq6gp14z535hazbri342qpns6c2j0mza92f";
    version = "79.0.3945.56";
  };
  dev = {
    sha256 = "1l6dsv9cv5gqd682mkawwd15x82f0m6rmnb0mig0lv84p89zpxz2";
    sha256bin64 = "1kbd000friz68fbgkrkgsdhcx17l4ar2s1bfzr34ckab2785g5ni";
    version = "80.0.3970.5";
  };
  stable = {
    sha256 = "03jvfz68nvmmrplygf96sh0l347p4h03c8vpw8yrglh6ycwkiigr";
    sha256bin64 = "1knsrdh4vj1zl3v1frzrvzg0pwb64zhq2il7pwskrfcbmsj3gkh6";
    version = "78.0.3904.108";
  };
}
